pref("perspectives.quorum_thresh", 75);
pref("perspectives.required_duration", 0);
pref("perspectives.security_settings", 1);
pref("perspectives.exceptions.permanent", false);
pref("perspectives.exceptions.enabled", true);
pref("perspectives.check_good_certificates", true);
pref("perspectives.require_user_permission", false);
pref("perspectives.show_label", true);
pref("perspectives.svg", "");
pref("perspectives.max_timespan_for_inconsistency_test", 7);
pref("perspectives.weak_consistency_time_limit", 30);
pref("perspectives.trust_https_with_weak_consistency", true);
pref("perspectives.max_cache_age_sec", 10000);
pref("perspectives.whitelist", "");
pref("perspectives.prompt_update_all_https_setting", true);
pref("perspectives.additional_notary_list", "");
pref("perspectives.default_notary_list",""); 
pref("perspectives.use_default_notary_list",true); 
pref("perspectives.enable_default_list_auto_update",false); 
pref("perspectives.first_run", true);

